### ISSUE TITLE
scoring-hsps

### ISSUE THREAD

**Issue by jessb0t** [NDCLab/instruments#42]
**Scoring Instructions**

One total averaged score:
hsps_scrdTot_sx_rx_ex

Three  subscores:
hsps_scrdEoe_sx_rx_ex (Ease of Excitation) (average of items: 3, 4, 13, 14, 16, 17, 20, 21, 23, 24, 26, 27)

hsps_scrdAes_sx_rx_ex (Aesthetic Sensitivity) (average of items: 2, 8, 10, 12, 15, 22, 5)

hsps_scrdLst_sx_rx_ex (Low Sensory Threshold) (average of items: 6, 7, 9, 18, 19, 25)

_To calculate partials:_

Calculate percentage complete (0-1) for each subscore:
hsps_percTot_sx_rx_ex
hsps_percEoe_sx_rx_ex
hsps_percAes_sx_rx_ex
hsps_percLst_sx_rx_ex

If greater than or equal to 0.8, compute subscore. If less than 0.8, do not compute subscore.

Done Defined:

- hsps added to the scoring script on dev-script (OP/FS)

- hsps added to dev-uploads (PDF, REDCap zip, readme) (JA/ALN)

**Comment by anaNDClab** [comment]
Hey @georgebuzzell, I am currently working on the scoring instructions for the HPS scale. However, the questionnaire does not offer any scoring instructions, and the questionnaire seems to come from a book. Therefore, I don't have access to any explanation on how the scoring for this questionnaire might work. I was wondering do you have access to the book related to this questionnaire, which is written by Aron?

**Comment by georgebuzzell** [comment]
@anaNDClab great question! Please follow the guidelines of this later paper:
https://www.sciencedirect.com/science/article/pii/S0191886905003909?casa_token=RATKaP4MLxsAAAAA:s41YvdbwzWpPd02A7lYAbES4oaNb3QafhZiXqidRsTeaWEAk5HNq31buxNm8oIDjG2cTLR-S

Please compute a total (average score) based on all 27 items, as well as three factor scores, each computed as averages. Note that the three factor scores only use a total of 25 of the 27 items.

Pasted from the article:

<p style="box-sizing: border-box; margin: 0px 0px 16px; padding: 0px; color: rgb(46, 46, 46); font-family: NexusSerif, Georgia, &quot;Times New Roman&quot;, Times, STIXGeneral, &quot;Cambria Math&quot;, &quot;Lucida Sans Unicode&quot;, &quot;Microsoft Sans Serif&quot;, &quot;Segoe UI Symbol&quot;, &quot;Arial Unicode MS&quot;, serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><a name="btbl1" href="https://www.sciencedirect.com/science/article/pii/S0191886905003909?casa_token=RATKaP4MLxsAAAAA:s41YvdbwzWpPd02A7lYAbES4oaNb3QafhZiXqidRsTeaWEAk5HNq31buxNm8oIDjG2cTLR-S#tbl1" class="workspace-trigger" style="box-sizing: border-box; margin: 0px; padding: 0px; background-color: transparent; text-decoration: none; color: rgb(12, 125, 187); word-break: break-word;">Table 1</a><span> </span>shows the rotated components and their respective items. Component 1, labeled Ease of Excitation (EOE), included 12 items related to becoming mentally overwhelmed by external (e.g., “Do you find it unpleasant to have a lot going on at once?”) and internal (e.g., “Does being hungry create a strong reaction in you, disrupting your concentration or mood?”) demands. Component 2, labeled Aesthetic Sensitivity (AES), included 7 items related to aesthetic awareness (e.g., “Are you deeply moved by arts and music?”). Component 3, labeled Low Sensory Threshold (LST), consisted of 6 items related to unpleasant sensory arousal to external stimuli (e.g., “Are you easily overwhelmed by things like bright lights, strong smells, coarse fabrics, or sirens close by?”).<span> </span><a name="btbl1" href="https://www.sciencedirect.com/science/article/pii/S0191886905003909?casa_token=RATKaP4MLxsAAAAA:s41YvdbwzWpPd02A7lYAbES4oaNb3QafhZiXqidRsTeaWEAk5HNq31buxNm8oIDjG2cTLR-S#tbl1" class="workspace-trigger" style="box-sizing: border-box; margin: 0px; padding: 0px; background-color: transparent; text-decoration: none; color: rgb(12, 125, 187); word-break: break-word;">Table 1</a><span> </span>also provides mean inter-item correlations and alphas for each of the three components, showing that they have good internal consistency. The components themselves were modestly intercorrelated: EOE correlated .32 with both AES and LST, and the latter two correlated .23.</p><div class="tables frame-topbot rowsep-0 colsep-0" id="tbl1" style="box-sizing: border-box; margin: 16px 0px; padding: 0px; border-top: 2px solid rgb(235, 235, 235); border-bottom: 2px solid rgb(235, 235, 235); font-size: 14px; color: rgb(46, 46, 46); font-family: NexusSerif, Georgia, &quot;Times New Roman&quot;, Times, STIXGeneral, &quot;Cambria Math&quot;, &quot;Lucida Sans Unicode&quot;, &quot;Microsoft Sans Serif&quot;, &quot;Segoe UI Symbol&quot;, &quot;Arial Unicode MS&quot;, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><span class="captions" style="box-sizing: border-box; margin: 16px 24px; padding: 0px; line-height: 22px; color: rgb(46, 46, 46); font-size: 16px;"><span style="box-sizing: border-box; margin: 0px; padding: 0px;"><p style="box-sizing: border-box; margin: 0px 0px 16px; padding: 0px;"><span class="label" style="box-sizing: border-box; margin: 0px; padding: 0px; font-size: 14px;">Table 1</span>.<span> </span>Principal components analysis with oblimin rotation (pattern matrix): Component loadings, alphas, and mean inter-item correlations for the HSPS (exploratory split-half sample)</p></span></span><div class="groups" style="box-sizing: border-box; margin: 16px 0px; padding: 0px; overflow-x: auto;">

Item | Components
-- | --

3. | Do other people’s moods affect you? | .36 |   |  
4. | Do you tend to be more sensitive to pain? | .36 |   |  
13. | Do you startle easily? | .42 |   |  
14. | Do you get rattled when you have a lot to do in a short amount of time? | .68 |   |  
16. | Are you annoyed when people try to get you to do too many things at once? | .62 |   |  
17. | Do you try hard to avoid making mistakes or forgetting things? | .36 |   |  
20. | Does being very hungry create a strong reaction in you, disrupting your concentration or mood? | .56 |   |  
21. | Do changes in your life shake you up? | .65 |   |  
23. | Do you find it unpleasant to have a lot going on at once? | .68 |   |  
24. | Do you make it a high priority to arrange your life to avoid upsetting or overwhelming situations? | .36 |   |  
26. | When you must compete or be observed while performing a task, do you become so nervous or shaky that you do much worse than you would otherwise? | .58 |   |  
27. | When you were a child, did your parents or teachers seem to see you as sensitive or shy? | .47 |   |  
2. | Do you seem to be aware of subtleties in your environment? |   | .65 |  
8. | Do you have a rich, complex inner life? |   | .76 |  
10. | Are you deeply moved by the arts or music? |   | .69 |  
12. | Are you conscientious? |   | .53 |  
15. | When people are uncomfortable in a physical environment do you tend to know what needs to be done to make it more comfortable (like changing the lighting or the seating)? |   | .53 |  
22. | Do you notice and enjoy delicate or fine scents, tastes, sounds, works of art? |   | .68 |  
5. | Do you find yourself needing to withdraw during busy days, into bed or into a darkened room or any place where you can have some privacy and relief from stimulation? |   | .39 |  
6. | Are you particularly sensitive to the effects of caffeine? |   |   | .70
7. | Are you easily overwhelmed by things like bright lights, strong smells, coarse fabrics, or sirens close by? |   |   | .70
9. | Are you made uncomfortable by loud noises? |   |   | .70
18. | Do you make a point to avoid violent movies and TV shows? |   |   | .57
19. | Do you become unpleasantly aroused when a lot is going on around you? |   |   | .53
25. | Are you bothered by intense stimuli, like loud noises or chaotic scenes? |   |   | .74
  |   |   |   |  
Coefficient alpha | .81 | .72 | .78
Mean inter-item correlation | .26 | .30 | .34

</div><p class="legend" style="box-sizing: border-box; margin: 0px 0px 16px; padding: 0px; color: rgb(46, 46, 46);"><p style="box-sizing: border-box; margin: 0px 0px 16px; padding: 0px;"><em style="box-sizing: border-box; margin: 0px; padding: 0px;">Note:</em><span> </span>EOE = Ease of Excitation; AES = Aesthetic Sensitivity; LST = Low Sensory Threshold;<span> </span><em style="box-sizing: border-box; margin: 0px; padding: 0px;">N</em> = 380.</p></p></div>[Table 1](https://www.sciencedirect.com/science/article/pii/S0191886905003909?casa_token=RATKaP4MLxsAAAAA:s41YvdbwzWpPd02A7lYAbES4oaNb3QafhZiXqidRsTeaWEAk5HNq31buxNm8oIDjG2cTLR-S#tbl1) shows the rotated components and their respective items. Component 1, labeled Ease of Excitation (EOE), included 12 items related to becoming mentally overwhelmed by external (e.g., “Do you find it unpleasant to have a lot going on at once?”) and internal (e.g., “Does being hungry create a strong reaction in you, disrupting your concentration or mood?”) demands. Component 2, labeled Aesthetic Sensitivity (AES), included 7 items related to aesthetic awareness (e.g., “Are you deeply moved by arts and music?”). Component 3, labeled Low Sensory Threshold (LST), consisted of 6 items related to unpleasant sensory arousal to external stimuli (e.g., “Are you easily overwhelmed by things like bright lights, strong smells, coarse fabrics, or sirens close by?”). [Table 1](https://www.sciencedirect.com/science/article/pii/S0191886905003909?casa_token=RATKaP4MLxsAAAAA:s41YvdbwzWpPd02A7lYAbES4oaNb3QafhZiXqidRsTeaWEAk5HNq31buxNm8oIDjG2cTLR-S#tbl1) also provides mean inter-item correlations and alphas for each of the three components, showing that they have good internal consistency. The components themselves were modestly intercorrelated: EOE correlated .32 with both AES and LST, and the latter two correlated .23.

Table 1. Principal components analysis with oblimin rotation (pattern matrix): Component loadings, alphas, and mean inter-item correlations for the HSPS (exploratory split-half sample)

Item	Components
1 (EOE)	2 (AES)	3 (LST)
3.	Do other people’s moods affect you?	.36		
4.	Do you tend to be more sensitive to pain?	.36		
13.	Do you startle easily?	.42		
14.	Do you get rattled when you have a lot to do in a short amount of time?	.68		
16.	Are you annoyed when people try to get you to do too many things at once?	.62		
17.	Do you try hard to avoid making mistakes or forgetting things?	.36		
20.	Does being very hungry create a strong reaction in you, disrupting your concentration or mood?	.56		
21.	Do changes in your life shake you up?	.65		
23.	Do you find it unpleasant to have a lot going on at once?	.68		
24.	Do you make it a high priority to arrange your life to avoid upsetting or overwhelming situations?	.36		
26.	When you must compete or be observed while performing a task, do you become so nervous or shaky that you do much worse than you would otherwise?	.58		
27.	When you were a child, did your parents or teachers seem to see you as sensitive or shy?	.47		
2.	Do you seem to be aware of subtleties in your environment?		.65	
8.	Do you have a rich, complex inner life?		.76	
10.	Are you deeply moved by the arts or music?		.69	
12.	Are you conscientious?		.53	
15.	When people are uncomfortable in a physical environment do you tend to know what needs to be done to make it more comfortable (like changing the lighting or the seating)?		.53	
22.	Do you notice and enjoy delicate or fine scents, tastes, sounds, works of art?		.68	
5.	Do you find yourself needing to withdraw during busy days, into bed or into a darkened room or any place where you can have some privacy and relief from stimulation?		.39	
6.	Are you particularly sensitive to the effects of caffeine?			.70
7.	Are you easily overwhelmed by things like bright lights, strong smells, coarse fabrics, or sirens close by?			.70
9.	Are you made uncomfortable by loud noises?			.70
18.	Do you make a point to avoid violent movies and TV shows?			.57
19.	Do you become unpleasantly aroused when a lot is going on around you?			.53
25.	Are you bothered by intense stimuli, like loud noises or chaotic scenes?			.74

Coefficient alpha	.81	.72	.78
Mean inter-item correlation	.26	.30	.34
Note: EOE = Ease of Excitation; AES = Aesthetic Sensitivity; LST = Low Sensory Threshold; N = 380.

**Comment by anaNDClab** [comment]
Thank you @georgebuzzell for the feedback! I just pasted the scoring instructions above. Could you and @jessb0t take a look at them and tell me if everything looks good?

**Comment by jessb0t** [comment]
@anaNDClab This looks good to me!  I'm adding the citation and link here for ease of reference when building out the readme:

https://www.sciencedirect.com/science/article/pii/S0191886905003909

Smolewska, K., McCabe, S.B., & Woody, E. (2006). A psychometric evaluation of the Highly Sensitive Person Scale: The components of sensory-processing sensitivity and their relation to the BIS/BAS and “Big Five”. Personality and Individual Differences, 40, 1269-1279.
